const { EMAIL, NAME, BREVO_API_KEY, URL, JWT_SECRET, DATABASE_URL, PORT_SECOND , PORT} = process.env;

module.exports = {
    EMAIL: `${EMAIL}`, NAME: `${NAME}`, BREVO_API_KEY: `${BREVO_API_KEY}`, URL: `${URL}`, JWT_SECRET: `${JWT_SECRET}`, DATABASE_URL: `${DATABASE_URL}`, PORT_SECOND, PORT
};
